//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wintac_utils.WintacReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wintac.com/", ConfigurationName="WintacReference.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_tech", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_tech();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_tech", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_techAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_jobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_jobs(bool is_admin, string userid, System.DateTime from_date, System.DateTime to_date, bool invoices, bool proposals, long last_cn, long last_no, long number_of_records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_jobs", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_jobsAsync(bool is_admin, string userid, System.DateTime from_date, System.DateTime to_date, bool invoices, bool proposals, long last_cn, long last_no, long number_of_records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_job_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_job_details(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_job_details", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_job_detailsAsync(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_techs_job", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object list_techs_job(System.DateTime job_date, long job_counter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_techs_job", ReplyAction="*")]
        System.Threading.Tasks.Task<object> list_techs_jobAsync(System.DateTime job_date, long job_counter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Authenticate(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_site_history", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_site_history(long job_cn, string job_name, System.DateTime from_date, System.DateTime to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_site_history", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_site_historyAsync(long job_cn, string job_name, System.DateTime from_date, System.DateTime to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/has_flatrate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string has_flatrate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/has_flatrate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> has_flatrateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_permissions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object get_permissions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_permissions", ReplyAction="*")]
        System.Threading.Tasks.Task<object> get_permissionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_job_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_job_status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_job_status", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_job_statusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_summary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_summary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_summary", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_summaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_sales_person", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_sales_person();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_sales_person", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_sales_personAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_project_manager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_project_manager();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_project_manager", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_project_managerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_account_manager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_account_manager();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_account_manager", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_account_managerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_payment_ref", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_payment_ref();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_payment_ref", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_payment_refAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_udf1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf1", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_udf1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_udf2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_udf2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_udf3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf3", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_udf3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_udf4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf4", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_udf4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_udf5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_udf5", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_udf5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_udf1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf1", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_udf1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_udf2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_udf2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_udf3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf3", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_udf3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_udf4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf4", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_udf4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_udf5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_udf5", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_udf5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_mfg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_mfg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_mfg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_mfgAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_vdr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_vdr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_vdr", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_vdrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_grp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_grp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_grp", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_grpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_dept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_dept();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_dept", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_deptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_office_loc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_office_loc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_office_loc", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_office_locAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_tech_loc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_tech_loc(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_tech_loc", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_tech_locAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_site_info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_site_info(long cn, string job_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_site_info", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_site_infoAsync(long cn, string job_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_job", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string add_job(
                    long job_cn, 
                    long job_no2, 
                    string job_name, 
                    string job_adr1, 
                    string job_adr2, 
                    string job_city, 
                    string job_state, 
                    string job_zip, 
                    string job_phone1, 
                    string job_phone2, 
                    System.DateTime job_date, 
                    string job_status, 
                    string start_time, 
                    string end_time, 
                    string summary, 
                    string po_number, 
                    string sales_person, 
                    string project_manager, 
                    string workdescription, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_job", ReplyAction="*")]
        System.Threading.Tasks.Task<string> add_jobAsync(
                    long job_cn, 
                    long job_no2, 
                    string job_name, 
                    string job_adr1, 
                    string job_adr2, 
                    string job_city, 
                    string job_state, 
                    string job_zip, 
                    string job_phone1, 
                    string job_phone2, 
                    System.DateTime job_date, 
                    string job_status, 
                    string start_time, 
                    string end_time, 
                    string summary, 
                    string po_number, 
                    string sales_person, 
                    string project_manager, 
                    string workdescription, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_time_material", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_time_material(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_time_material", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_time_materialAsync(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_type(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_type", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_typeAsync(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/edit_time_material", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string edit_time_material(
                    long job_cn, 
                    long job_no, 
                    long item_pagenum, 
                    string item_vdr, 
                    string item_grp, 
                    string item_mfg, 
                    string item_dept, 
                    string item_ic, 
                    string item_iu, 
                    string item_ud1, 
                    string item_ud2, 
                    string item_ud3, 
                    string item_ud4, 
                    string item_ud5, 
                    string item_mn, 
                    string item_sn, 
                    string item_desc, 
                    long item_type, 
                    System.DateTime item_idate, 
                    string item_note, 
                    double item_price, 
                    double item_qty, 
                    double item_cost, 
                    bool item_tax1, 
                    bool item_tax2, 
                    bool item_tax3, 
                    bool item_tax4, 
                    bool item_tax5, 
                    bool item_do_not_print);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/edit_time_material", ReplyAction="*")]
        System.Threading.Tasks.Task<string> edit_time_materialAsync(
                    long job_cn, 
                    long job_no, 
                    long item_pagenum, 
                    string item_vdr, 
                    string item_grp, 
                    string item_mfg, 
                    string item_dept, 
                    string item_ic, 
                    string item_iu, 
                    string item_ud1, 
                    string item_ud2, 
                    string item_ud3, 
                    string item_ud4, 
                    string item_ud5, 
                    string item_mn, 
                    string item_sn, 
                    string item_desc, 
                    long item_type, 
                    System.DateTime item_idate, 
                    string item_note, 
                    double item_price, 
                    double item_qty, 
                    double item_cost, 
                    bool item_tax1, 
                    bool item_tax2, 
                    bool item_tax3, 
                    bool item_tax4, 
                    bool item_tax5, 
                    bool item_do_not_print);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_time_material", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_time_material(long job_cn, long job_no, long item_pagenum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_time_material", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_time_materialAsync(long job_cn, long job_no, long item_pagenum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_installed_equipment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_installed_equipment(long job_cn, long job_no, string job_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_installed_equipment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_installed_equipmentAsync(long job_cn, long job_no, string job_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_task_groups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_task_groups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_task_groups", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_task_groupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_code", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_code(long job_cn, long job_no, string search_string, string last_item, long number_of_records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_code", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_codeAsync(long job_cn, long job_no, string search_string, string last_item, long number_of_records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_description", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_item_description(long job_cn, long job_no, string search_string, string last_item, long number_of_records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_item_description", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_item_descriptionAsync(long job_cn, long job_no, string search_string, string last_item, long number_of_records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_pictures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_pictures(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_pictures", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_picturesAsync(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_attachments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_attachments(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_attachments", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_attachmentsAsync(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/has_signature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string has_signature(long job_cn, long job_no, long job_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/has_signature", ReplyAction="*")]
        System.Threading.Tasks.Task<string> has_signatureAsync(long job_cn, long job_no, long job_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_balance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_balance(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_balance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_balanceAsync(long job_cn, long job_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/apply_payment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string apply_payment(long job_cn, long job_no, double amtpay, string payment_ref, string chk_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/apply_payment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> apply_paymentAsync(long job_cn, long job_no, double amtpay, string payment_ref, string chk_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Clock_in", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Clock_in(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Clock_in", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Clock_inAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Clock_out", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Clock_out(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Clock_out", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Clock_outAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/break_start_end", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string break_start_end(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/break_start_end", ReplyAction="*")]
        System.Threading.Tasks.Task<string> break_start_endAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Checkstatus_clockin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Checkstatus_clockin(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Checkstatus_clockin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Checkstatus_clockinAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Checkstatus_Break", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Checkstatus_Break(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Checkstatus_Break", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Checkstatus_BreakAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_customers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_customers(string search_string, long page_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_customers", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_customersAsync(string search_string, long page_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_customer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_customer(long customer_cn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_customer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_customerAsync(long customer_cn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_job_sites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_job_sites(long cn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_job_sites", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_job_sitesAsync(long cn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_ref_code", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_ref_code();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_ref_code", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_ref_codeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_business", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_business();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_business", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_businessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_time_material", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object add_time_material(
                    string userid, 
                    long item_cn, 
                    long item_no, 
                    string item_code, 
                    string description, 
                    string item_type, 
                    double cost, 
                    double qty, 
                    double price, 
                    string units, 
                    string model_no, 
                    string serial_no, 
                    string type, 
                    bool tax1, 
                    bool tax2, 
                    bool tax3, 
                    bool tax4, 
                    bool tax5, 
                    bool print_on_wip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_time_material", ReplyAction="*")]
        System.Threading.Tasks.Task<object> add_time_materialAsync(
                    string userid, 
                    long item_cn, 
                    long item_no, 
                    string item_code, 
                    string description, 
                    string item_type, 
                    double cost, 
                    double qty, 
                    double price, 
                    string units, 
                    string model_no, 
                    string serial_no, 
                    string type, 
                    bool tax1, 
                    bool tax2, 
                    bool tax3, 
                    bool tax4, 
                    bool tax5, 
                    bool print_on_wip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_task_group", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object add_task_group(string userid, long job_cn, long job_no, long Lid, long multiplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_task_group", ReplyAction="*")]
        System.Threading.Tasks.Task<object> add_task_groupAsync(string userid, long job_cn, long job_no, long Lid, long multiplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_customer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string add_customer(
                    string first_name, 
                    string last_name, 
                    string tag_code, 
                    string ref_code, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string county, 
                    string sal, 
                    string acct_manager, 
                    string phone1, 
                    string phone2, 
                    string phone3, 
                    string phone4, 
                    string email1, 
                    string email2, 
                    string business, 
                    string misc1, 
                    string misc2, 
                    bool WO, 
                    double taxpct1, 
                    double taxpct2, 
                    double taxpct3, 
                    double taxpct4, 
                    double taxpct5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/add_customer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> add_customerAsync(
                    string first_name, 
                    string last_name, 
                    string tag_code, 
                    string ref_code, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string county, 
                    string sal, 
                    string acct_manager, 
                    string phone1, 
                    string phone2, 
                    string phone3, 
                    string phone4, 
                    string email1, 
                    string email2, 
                    string business, 
                    string misc1, 
                    string misc2, 
                    bool WO, 
                    double taxpct1, 
                    double taxpct2, 
                    double taxpct3, 
                    double taxpct4, 
                    double taxpct5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/select_equipment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string select_equipment(long job_cn, long job_no, string item_ic, string item_name, string item_mn, string item_sn, string item_wdate, string item_wldate, string item_note, long item_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/select_equipment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> select_equipmentAsync(long job_cn, long job_no, string item_ic, string item_name, string item_mn, string item_sn, string item_wdate, string item_wldate, string item_note, long item_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/equipment_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string equipment_details(long job_cn, long job_no, long page_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/equipment_details", ReplyAction="*")]
        System.Threading.Tasks.Task<string> equipment_detailsAsync(long job_cn, long job_no, long page_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/service_history", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string service_history(string job_name, long cn, string model_no, string serial_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/service_history", ReplyAction="*")]
        System.Threading.Tasks.Task<string> service_historyAsync(string job_name, long cn, string model_no, string serial_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_user_defined_titles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_user_defined_titles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_user_defined_titles", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_user_defined_titlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Delete_item", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Delete_item(string userid, long job_cn, long job_no, string item_code, long page_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/Delete_item", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Delete_itemAsync(string userid, long job_cn, long job_no, string item_code, long page_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_inventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string list_inventory(string ic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/list_inventory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> list_inventoryAsync(string ic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/process_job", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string process_job(
                    string userid, 
                    long job_counter, 
                    string job_type, 
                    long job_cn, 
                    long job_no, 
                    System.DateTime job_date, 
                    string job_status, 
                    string job_summary, 
                    string project_manager, 
                    string po_number, 
                    string work_description, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    long tech1_counter, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    long tech2_counter, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    long tech3_counter, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    long tech4_counter, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    long tech5_counter, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/process_job", ReplyAction="*")]
        System.Threading.Tasks.Task<string> process_jobAsync(
                    string userid, 
                    long job_counter, 
                    string job_type, 
                    long job_cn, 
                    long job_no, 
                    System.DateTime job_date, 
                    string job_status, 
                    string job_summary, 
                    string project_manager, 
                    string po_number, 
                    string work_description, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    long tech1_counter, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    long tech2_counter, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    long tech3_counter, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    long tech4_counter, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    long tech5_counter, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/process_tm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string process_tm(string userid, long job_cn, long job_no, string job_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/process_tm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> process_tmAsync(string userid, long job_cn, long job_no, string job_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_signature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_signature(long customerNumber, long jobNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_signature", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_signatureAsync(long customerNumber, long jobNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/savesignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string savesignature(long job_cn, long job_no, int frm, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/savesignature", ReplyAction="*")]
        System.Threading.Tasks.Task<string> savesignatureAsync(long job_cn, long job_no, int frm, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/savefiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string savefiles(long job_cn, string job_no, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/savefiles", ReplyAction="*")]
        System.Threading.Tasks.Task<string> savefilesAsync(long job_cn, string job_no, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_time", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_time();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wintac.com/get_time", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_timeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : wintac_utils.WintacReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<wintac_utils.WintacReference.WebService1Soap>, wintac_utils.WintacReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string list_tech() {
            return base.Channel.list_tech();
        }
        
        public System.Threading.Tasks.Task<string> list_techAsync() {
            return base.Channel.list_techAsync();
        }
        
        public string list_jobs(bool is_admin, string userid, System.DateTime from_date, System.DateTime to_date, bool invoices, bool proposals, long last_cn, long last_no, long number_of_records) {
            return base.Channel.list_jobs(is_admin, userid, from_date, to_date, invoices, proposals, last_cn, last_no, number_of_records);
        }
        
        public System.Threading.Tasks.Task<string> list_jobsAsync(bool is_admin, string userid, System.DateTime from_date, System.DateTime to_date, bool invoices, bool proposals, long last_cn, long last_no, long number_of_records) {
            return base.Channel.list_jobsAsync(is_admin, userid, from_date, to_date, invoices, proposals, last_cn, last_no, number_of_records);
        }
        
        public string get_job_details(long job_cn, long job_no) {
            return base.Channel.get_job_details(job_cn, job_no);
        }
        
        public System.Threading.Tasks.Task<string> get_job_detailsAsync(long job_cn, long job_no) {
            return base.Channel.get_job_detailsAsync(job_cn, job_no);
        }
        
        public object list_techs_job(System.DateTime job_date, long job_counter) {
            return base.Channel.list_techs_job(job_date, job_counter);
        }
        
        public System.Threading.Tasks.Task<object> list_techs_jobAsync(System.DateTime job_date, long job_counter) {
            return base.Channel.list_techs_jobAsync(job_date, job_counter);
        }
        
        public string Authenticate(string username, string password) {
            return base.Channel.Authenticate(username, password);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string username, string password) {
            return base.Channel.AuthenticateAsync(username, password);
        }
        
        public string list_site_history(long job_cn, string job_name, System.DateTime from_date, System.DateTime to_date) {
            return base.Channel.list_site_history(job_cn, job_name, from_date, to_date);
        }
        
        public System.Threading.Tasks.Task<string> list_site_historyAsync(long job_cn, string job_name, System.DateTime from_date, System.DateTime to_date) {
            return base.Channel.list_site_historyAsync(job_cn, job_name, from_date, to_date);
        }
        
        public string has_flatrate() {
            return base.Channel.has_flatrate();
        }
        
        public System.Threading.Tasks.Task<string> has_flatrateAsync() {
            return base.Channel.has_flatrateAsync();
        }
        
        public object get_permissions() {
            return base.Channel.get_permissions();
        }
        
        public System.Threading.Tasks.Task<object> get_permissionsAsync() {
            return base.Channel.get_permissionsAsync();
        }
        
        public string list_job_status() {
            return base.Channel.list_job_status();
        }
        
        public System.Threading.Tasks.Task<string> list_job_statusAsync() {
            return base.Channel.list_job_statusAsync();
        }
        
        public string list_summary() {
            return base.Channel.list_summary();
        }
        
        public System.Threading.Tasks.Task<string> list_summaryAsync() {
            return base.Channel.list_summaryAsync();
        }
        
        public string list_sales_person() {
            return base.Channel.list_sales_person();
        }
        
        public System.Threading.Tasks.Task<string> list_sales_personAsync() {
            return base.Channel.list_sales_personAsync();
        }
        
        public string list_project_manager() {
            return base.Channel.list_project_manager();
        }
        
        public System.Threading.Tasks.Task<string> list_project_managerAsync() {
            return base.Channel.list_project_managerAsync();
        }
        
        public string list_account_manager() {
            return base.Channel.list_account_manager();
        }
        
        public System.Threading.Tasks.Task<string> list_account_managerAsync() {
            return base.Channel.list_account_managerAsync();
        }
        
        public string list_payment_ref() {
            return base.Channel.list_payment_ref();
        }
        
        public System.Threading.Tasks.Task<string> list_payment_refAsync() {
            return base.Channel.list_payment_refAsync();
        }
        
        public string list_udf1() {
            return base.Channel.list_udf1();
        }
        
        public System.Threading.Tasks.Task<string> list_udf1Async() {
            return base.Channel.list_udf1Async();
        }
        
        public string list_udf2() {
            return base.Channel.list_udf2();
        }
        
        public System.Threading.Tasks.Task<string> list_udf2Async() {
            return base.Channel.list_udf2Async();
        }
        
        public string list_udf3() {
            return base.Channel.list_udf3();
        }
        
        public System.Threading.Tasks.Task<string> list_udf3Async() {
            return base.Channel.list_udf3Async();
        }
        
        public string list_udf4() {
            return base.Channel.list_udf4();
        }
        
        public System.Threading.Tasks.Task<string> list_udf4Async() {
            return base.Channel.list_udf4Async();
        }
        
        public string list_udf5() {
            return base.Channel.list_udf5();
        }
        
        public System.Threading.Tasks.Task<string> list_udf5Async() {
            return base.Channel.list_udf5Async();
        }
        
        public string list_item_udf1() {
            return base.Channel.list_item_udf1();
        }
        
        public System.Threading.Tasks.Task<string> list_item_udf1Async() {
            return base.Channel.list_item_udf1Async();
        }
        
        public string list_item_udf2() {
            return base.Channel.list_item_udf2();
        }
        
        public System.Threading.Tasks.Task<string> list_item_udf2Async() {
            return base.Channel.list_item_udf2Async();
        }
        
        public string list_item_udf3() {
            return base.Channel.list_item_udf3();
        }
        
        public System.Threading.Tasks.Task<string> list_item_udf3Async() {
            return base.Channel.list_item_udf3Async();
        }
        
        public string list_item_udf4() {
            return base.Channel.list_item_udf4();
        }
        
        public System.Threading.Tasks.Task<string> list_item_udf4Async() {
            return base.Channel.list_item_udf4Async();
        }
        
        public string list_item_udf5() {
            return base.Channel.list_item_udf5();
        }
        
        public System.Threading.Tasks.Task<string> list_item_udf5Async() {
            return base.Channel.list_item_udf5Async();
        }
        
        public string list_item_mfg() {
            return base.Channel.list_item_mfg();
        }
        
        public System.Threading.Tasks.Task<string> list_item_mfgAsync() {
            return base.Channel.list_item_mfgAsync();
        }
        
        public string list_item_vdr() {
            return base.Channel.list_item_vdr();
        }
        
        public System.Threading.Tasks.Task<string> list_item_vdrAsync() {
            return base.Channel.list_item_vdrAsync();
        }
        
        public string list_item_grp() {
            return base.Channel.list_item_grp();
        }
        
        public System.Threading.Tasks.Task<string> list_item_grpAsync() {
            return base.Channel.list_item_grpAsync();
        }
        
        public string list_item_dept() {
            return base.Channel.list_item_dept();
        }
        
        public System.Threading.Tasks.Task<string> list_item_deptAsync() {
            return base.Channel.list_item_deptAsync();
        }
        
        public string get_office_loc() {
            return base.Channel.get_office_loc();
        }
        
        public System.Threading.Tasks.Task<string> get_office_locAsync() {
            return base.Channel.get_office_locAsync();
        }
        
        public string get_tech_loc(string userid) {
            return base.Channel.get_tech_loc(userid);
        }
        
        public System.Threading.Tasks.Task<string> get_tech_locAsync(string userid) {
            return base.Channel.get_tech_locAsync(userid);
        }
        
        public string get_site_info(long cn, string job_name) {
            return base.Channel.get_site_info(cn, job_name);
        }
        
        public System.Threading.Tasks.Task<string> get_site_infoAsync(long cn, string job_name) {
            return base.Channel.get_site_infoAsync(cn, job_name);
        }
        
        public string add_job(
                    long job_cn, 
                    long job_no2, 
                    string job_name, 
                    string job_adr1, 
                    string job_adr2, 
                    string job_city, 
                    string job_state, 
                    string job_zip, 
                    string job_phone1, 
                    string job_phone2, 
                    System.DateTime job_date, 
                    string job_status, 
                    string start_time, 
                    string end_time, 
                    string summary, 
                    string po_number, 
                    string sales_person, 
                    string project_manager, 
                    string workdescription, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5) {
            return base.Channel.add_job(job_cn, job_no2, job_name, job_adr1, job_adr2, job_city, job_state, job_zip, job_phone1, job_phone2, job_date, job_status, start_time, end_time, summary, po_number, sales_person, project_manager, workdescription, tech1, tech1_start_time, tech1_end_time, tech2, tech2_start_time, tech2_end_time, tech3, tech3_start_time, tech3_end_time, tech4, tech4_start_time, tech4_end_time, tech5, tech5_start_time, tech5_end_time, udf1, udf2, udf3, udf4, udf5);
        }
        
        public System.Threading.Tasks.Task<string> add_jobAsync(
                    long job_cn, 
                    long job_no2, 
                    string job_name, 
                    string job_adr1, 
                    string job_adr2, 
                    string job_city, 
                    string job_state, 
                    string job_zip, 
                    string job_phone1, 
                    string job_phone2, 
                    System.DateTime job_date, 
                    string job_status, 
                    string start_time, 
                    string end_time, 
                    string summary, 
                    string po_number, 
                    string sales_person, 
                    string project_manager, 
                    string workdescription, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5) {
            return base.Channel.add_jobAsync(job_cn, job_no2, job_name, job_adr1, job_adr2, job_city, job_state, job_zip, job_phone1, job_phone2, job_date, job_status, start_time, end_time, summary, po_number, sales_person, project_manager, workdescription, tech1, tech1_start_time, tech1_end_time, tech2, tech2_start_time, tech2_end_time, tech3, tech3_start_time, tech3_end_time, tech4, tech4_start_time, tech4_end_time, tech5, tech5_start_time, tech5_end_time, udf1, udf2, udf3, udf4, udf5);
        }
        
        public string list_time_material(long job_cn, long job_no) {
            return base.Channel.list_time_material(job_cn, job_no);
        }
        
        public System.Threading.Tasks.Task<string> list_time_materialAsync(long job_cn, long job_no) {
            return base.Channel.list_time_materialAsync(job_cn, job_no);
        }
        
        public string list_item_type(long job_cn, long job_no) {
            return base.Channel.list_item_type(job_cn, job_no);
        }
        
        public System.Threading.Tasks.Task<string> list_item_typeAsync(long job_cn, long job_no) {
            return base.Channel.list_item_typeAsync(job_cn, job_no);
        }
        
        public string edit_time_material(
                    long job_cn, 
                    long job_no, 
                    long item_pagenum, 
                    string item_vdr, 
                    string item_grp, 
                    string item_mfg, 
                    string item_dept, 
                    string item_ic, 
                    string item_iu, 
                    string item_ud1, 
                    string item_ud2, 
                    string item_ud3, 
                    string item_ud4, 
                    string item_ud5, 
                    string item_mn, 
                    string item_sn, 
                    string item_desc, 
                    long item_type, 
                    System.DateTime item_idate, 
                    string item_note, 
                    double item_price, 
                    double item_qty, 
                    double item_cost, 
                    bool item_tax1, 
                    bool item_tax2, 
                    bool item_tax3, 
                    bool item_tax4, 
                    bool item_tax5, 
                    bool item_do_not_print) {
            return base.Channel.edit_time_material(job_cn, job_no, item_pagenum, item_vdr, item_grp, item_mfg, item_dept, item_ic, item_iu, item_ud1, item_ud2, item_ud3, item_ud4, item_ud5, item_mn, item_sn, item_desc, item_type, item_idate, item_note, item_price, item_qty, item_cost, item_tax1, item_tax2, item_tax3, item_tax4, item_tax5, item_do_not_print);
        }
        
        public System.Threading.Tasks.Task<string> edit_time_materialAsync(
                    long job_cn, 
                    long job_no, 
                    long item_pagenum, 
                    string item_vdr, 
                    string item_grp, 
                    string item_mfg, 
                    string item_dept, 
                    string item_ic, 
                    string item_iu, 
                    string item_ud1, 
                    string item_ud2, 
                    string item_ud3, 
                    string item_ud4, 
                    string item_ud5, 
                    string item_mn, 
                    string item_sn, 
                    string item_desc, 
                    long item_type, 
                    System.DateTime item_idate, 
                    string item_note, 
                    double item_price, 
                    double item_qty, 
                    double item_cost, 
                    bool item_tax1, 
                    bool item_tax2, 
                    bool item_tax3, 
                    bool item_tax4, 
                    bool item_tax5, 
                    bool item_do_not_print) {
            return base.Channel.edit_time_materialAsync(job_cn, job_no, item_pagenum, item_vdr, item_grp, item_mfg, item_dept, item_ic, item_iu, item_ud1, item_ud2, item_ud3, item_ud4, item_ud5, item_mn, item_sn, item_desc, item_type, item_idate, item_note, item_price, item_qty, item_cost, item_tax1, item_tax2, item_tax3, item_tax4, item_tax5, item_do_not_print);
        }
        
        public string get_time_material(long job_cn, long job_no, long item_pagenum) {
            return base.Channel.get_time_material(job_cn, job_no, item_pagenum);
        }
        
        public System.Threading.Tasks.Task<string> get_time_materialAsync(long job_cn, long job_no, long item_pagenum) {
            return base.Channel.get_time_materialAsync(job_cn, job_no, item_pagenum);
        }
        
        public string list_installed_equipment(long job_cn, long job_no, string job_name) {
            return base.Channel.list_installed_equipment(job_cn, job_no, job_name);
        }
        
        public System.Threading.Tasks.Task<string> list_installed_equipmentAsync(long job_cn, long job_no, string job_name) {
            return base.Channel.list_installed_equipmentAsync(job_cn, job_no, job_name);
        }
        
        public string list_task_groups() {
            return base.Channel.list_task_groups();
        }
        
        public System.Threading.Tasks.Task<string> list_task_groupsAsync() {
            return base.Channel.list_task_groupsAsync();
        }
        
        public string list_item_code(long job_cn, long job_no, string search_string, string last_item, long number_of_records) {
            return base.Channel.list_item_code(job_cn, job_no, search_string, last_item, number_of_records);
        }
        
        public System.Threading.Tasks.Task<string> list_item_codeAsync(long job_cn, long job_no, string search_string, string last_item, long number_of_records) {
            return base.Channel.list_item_codeAsync(job_cn, job_no, search_string, last_item, number_of_records);
        }
        
        public string list_item_description(long job_cn, long job_no, string search_string, string last_item, long number_of_records) {
            return base.Channel.list_item_description(job_cn, job_no, search_string, last_item, number_of_records);
        }
        
        public System.Threading.Tasks.Task<string> list_item_descriptionAsync(long job_cn, long job_no, string search_string, string last_item, long number_of_records) {
            return base.Channel.list_item_descriptionAsync(job_cn, job_no, search_string, last_item, number_of_records);
        }
        
        public string list_pictures(long job_cn, long job_no) {
            return base.Channel.list_pictures(job_cn, job_no);
        }
        
        public System.Threading.Tasks.Task<string> list_picturesAsync(long job_cn, long job_no) {
            return base.Channel.list_picturesAsync(job_cn, job_no);
        }
        
        public string list_attachments(long job_cn, long job_no) {
            return base.Channel.list_attachments(job_cn, job_no);
        }
        
        public System.Threading.Tasks.Task<string> list_attachmentsAsync(long job_cn, long job_no) {
            return base.Channel.list_attachmentsAsync(job_cn, job_no);
        }
        
        public string has_signature(long job_cn, long job_no, long job_type) {
            return base.Channel.has_signature(job_cn, job_no, job_type);
        }
        
        public System.Threading.Tasks.Task<string> has_signatureAsync(long job_cn, long job_no, long job_type) {
            return base.Channel.has_signatureAsync(job_cn, job_no, job_type);
        }
        
        public string get_balance(long job_cn, long job_no) {
            return base.Channel.get_balance(job_cn, job_no);
        }
        
        public System.Threading.Tasks.Task<string> get_balanceAsync(long job_cn, long job_no) {
            return base.Channel.get_balanceAsync(job_cn, job_no);
        }
        
        public string apply_payment(long job_cn, long job_no, double amtpay, string payment_ref, string chk_num) {
            return base.Channel.apply_payment(job_cn, job_no, amtpay, payment_ref, chk_num);
        }
        
        public System.Threading.Tasks.Task<string> apply_paymentAsync(long job_cn, long job_no, double amtpay, string payment_ref, string chk_num) {
            return base.Channel.apply_paymentAsync(job_cn, job_no, amtpay, payment_ref, chk_num);
        }
        
        public string Clock_in(string userid) {
            return base.Channel.Clock_in(userid);
        }
        
        public System.Threading.Tasks.Task<string> Clock_inAsync(string userid) {
            return base.Channel.Clock_inAsync(userid);
        }
        
        public string Clock_out(string userid) {
            return base.Channel.Clock_out(userid);
        }
        
        public System.Threading.Tasks.Task<string> Clock_outAsync(string userid) {
            return base.Channel.Clock_outAsync(userid);
        }
        
        public string break_start_end(string userid) {
            return base.Channel.break_start_end(userid);
        }
        
        public System.Threading.Tasks.Task<string> break_start_endAsync(string userid) {
            return base.Channel.break_start_endAsync(userid);
        }
        
        public string Checkstatus_clockin(string userid) {
            return base.Channel.Checkstatus_clockin(userid);
        }
        
        public System.Threading.Tasks.Task<string> Checkstatus_clockinAsync(string userid) {
            return base.Channel.Checkstatus_clockinAsync(userid);
        }
        
        public string Checkstatus_Break(string userid) {
            return base.Channel.Checkstatus_Break(userid);
        }
        
        public System.Threading.Tasks.Task<string> Checkstatus_BreakAsync(string userid) {
            return base.Channel.Checkstatus_BreakAsync(userid);
        }
        
        public string list_customers(string search_string, long page_no) {
            return base.Channel.list_customers(search_string, page_no);
        }
        
        public System.Threading.Tasks.Task<string> list_customersAsync(string search_string, long page_no) {
            return base.Channel.list_customersAsync(search_string, page_no);
        }
        
        public string get_customer(long customer_cn) {
            return base.Channel.get_customer(customer_cn);
        }
        
        public System.Threading.Tasks.Task<string> get_customerAsync(long customer_cn) {
            return base.Channel.get_customerAsync(customer_cn);
        }
        
        public string list_job_sites(long cn) {
            return base.Channel.list_job_sites(cn);
        }
        
        public System.Threading.Tasks.Task<string> list_job_sitesAsync(long cn) {
            return base.Channel.list_job_sitesAsync(cn);
        }
        
        public string list_ref_code() {
            return base.Channel.list_ref_code();
        }
        
        public System.Threading.Tasks.Task<string> list_ref_codeAsync() {
            return base.Channel.list_ref_codeAsync();
        }
        
        public string list_business() {
            return base.Channel.list_business();
        }
        
        public System.Threading.Tasks.Task<string> list_businessAsync() {
            return base.Channel.list_businessAsync();
        }
        
        public object add_time_material(
                    string userid, 
                    long item_cn, 
                    long item_no, 
                    string item_code, 
                    string description, 
                    string item_type, 
                    double cost, 
                    double qty, 
                    double price, 
                    string units, 
                    string model_no, 
                    string serial_no, 
                    string type, 
                    bool tax1, 
                    bool tax2, 
                    bool tax3, 
                    bool tax4, 
                    bool tax5, 
                    bool print_on_wip) {
            return base.Channel.add_time_material(userid, item_cn, item_no, item_code, description, item_type, cost, qty, price, units, model_no, serial_no, type, tax1, tax2, tax3, tax4, tax5, print_on_wip);
        }
        
        public System.Threading.Tasks.Task<object> add_time_materialAsync(
                    string userid, 
                    long item_cn, 
                    long item_no, 
                    string item_code, 
                    string description, 
                    string item_type, 
                    double cost, 
                    double qty, 
                    double price, 
                    string units, 
                    string model_no, 
                    string serial_no, 
                    string type, 
                    bool tax1, 
                    bool tax2, 
                    bool tax3, 
                    bool tax4, 
                    bool tax5, 
                    bool print_on_wip) {
            return base.Channel.add_time_materialAsync(userid, item_cn, item_no, item_code, description, item_type, cost, qty, price, units, model_no, serial_no, type, tax1, tax2, tax3, tax4, tax5, print_on_wip);
        }
        
        public object add_task_group(string userid, long job_cn, long job_no, long Lid, long multiplier) {
            return base.Channel.add_task_group(userid, job_cn, job_no, Lid, multiplier);
        }
        
        public System.Threading.Tasks.Task<object> add_task_groupAsync(string userid, long job_cn, long job_no, long Lid, long multiplier) {
            return base.Channel.add_task_groupAsync(userid, job_cn, job_no, Lid, multiplier);
        }
        
        public string add_customer(
                    string first_name, 
                    string last_name, 
                    string tag_code, 
                    string ref_code, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string county, 
                    string sal, 
                    string acct_manager, 
                    string phone1, 
                    string phone2, 
                    string phone3, 
                    string phone4, 
                    string email1, 
                    string email2, 
                    string business, 
                    string misc1, 
                    string misc2, 
                    bool WO, 
                    double taxpct1, 
                    double taxpct2, 
                    double taxpct3, 
                    double taxpct4, 
                    double taxpct5) {
            return base.Channel.add_customer(first_name, last_name, tag_code, ref_code, address1, address2, city, state, zip, county, sal, acct_manager, phone1, phone2, phone3, phone4, email1, email2, business, misc1, misc2, WO, taxpct1, taxpct2, taxpct3, taxpct4, taxpct5);
        }
        
        public System.Threading.Tasks.Task<string> add_customerAsync(
                    string first_name, 
                    string last_name, 
                    string tag_code, 
                    string ref_code, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string county, 
                    string sal, 
                    string acct_manager, 
                    string phone1, 
                    string phone2, 
                    string phone3, 
                    string phone4, 
                    string email1, 
                    string email2, 
                    string business, 
                    string misc1, 
                    string misc2, 
                    bool WO, 
                    double taxpct1, 
                    double taxpct2, 
                    double taxpct3, 
                    double taxpct4, 
                    double taxpct5) {
            return base.Channel.add_customerAsync(first_name, last_name, tag_code, ref_code, address1, address2, city, state, zip, county, sal, acct_manager, phone1, phone2, phone3, phone4, email1, email2, business, misc1, misc2, WO, taxpct1, taxpct2, taxpct3, taxpct4, taxpct5);
        }
        
        public string select_equipment(long job_cn, long job_no, string item_ic, string item_name, string item_mn, string item_sn, string item_wdate, string item_wldate, string item_note, long item_type) {
            return base.Channel.select_equipment(job_cn, job_no, item_ic, item_name, item_mn, item_sn, item_wdate, item_wldate, item_note, item_type);
        }
        
        public System.Threading.Tasks.Task<string> select_equipmentAsync(long job_cn, long job_no, string item_ic, string item_name, string item_mn, string item_sn, string item_wdate, string item_wldate, string item_note, long item_type) {
            return base.Channel.select_equipmentAsync(job_cn, job_no, item_ic, item_name, item_mn, item_sn, item_wdate, item_wldate, item_note, item_type);
        }
        
        public string equipment_details(long job_cn, long job_no, long page_num) {
            return base.Channel.equipment_details(job_cn, job_no, page_num);
        }
        
        public System.Threading.Tasks.Task<string> equipment_detailsAsync(long job_cn, long job_no, long page_num) {
            return base.Channel.equipment_detailsAsync(job_cn, job_no, page_num);
        }
        
        public string service_history(string job_name, long cn, string model_no, string serial_no) {
            return base.Channel.service_history(job_name, cn, model_no, serial_no);
        }
        
        public System.Threading.Tasks.Task<string> service_historyAsync(string job_name, long cn, string model_no, string serial_no) {
            return base.Channel.service_historyAsync(job_name, cn, model_no, serial_no);
        }
        
        public string list_user_defined_titles() {
            return base.Channel.list_user_defined_titles();
        }
        
        public System.Threading.Tasks.Task<string> list_user_defined_titlesAsync() {
            return base.Channel.list_user_defined_titlesAsync();
        }
        
        public string Delete_item(string userid, long job_cn, long job_no, string item_code, long page_num) {
            return base.Channel.Delete_item(userid, job_cn, job_no, item_code, page_num);
        }
        
        public System.Threading.Tasks.Task<string> Delete_itemAsync(string userid, long job_cn, long job_no, string item_code, long page_num) {
            return base.Channel.Delete_itemAsync(userid, job_cn, job_no, item_code, page_num);
        }
        
        public string list_inventory(string ic) {
            return base.Channel.list_inventory(ic);
        }
        
        public System.Threading.Tasks.Task<string> list_inventoryAsync(string ic) {
            return base.Channel.list_inventoryAsync(ic);
        }
        
        public string process_job(
                    string userid, 
                    long job_counter, 
                    string job_type, 
                    long job_cn, 
                    long job_no, 
                    System.DateTime job_date, 
                    string job_status, 
                    string job_summary, 
                    string project_manager, 
                    string po_number, 
                    string work_description, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    long tech1_counter, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    long tech2_counter, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    long tech3_counter, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    long tech4_counter, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    long tech5_counter, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5) {
            return base.Channel.process_job(userid, job_counter, job_type, job_cn, job_no, job_date, job_status, job_summary, project_manager, po_number, work_description, tech1, tech1_start_time, tech1_end_time, tech1_counter, tech2, tech2_start_time, tech2_end_time, tech2_counter, tech3, tech3_start_time, tech3_end_time, tech3_counter, tech4, tech4_start_time, tech4_end_time, tech4_counter, tech5, tech5_start_time, tech5_end_time, tech5_counter, udf1, udf2, udf3, udf4, udf5);
        }
        
        public System.Threading.Tasks.Task<string> process_jobAsync(
                    string userid, 
                    long job_counter, 
                    string job_type, 
                    long job_cn, 
                    long job_no, 
                    System.DateTime job_date, 
                    string job_status, 
                    string job_summary, 
                    string project_manager, 
                    string po_number, 
                    string work_description, 
                    string tech1, 
                    string tech1_start_time, 
                    string tech1_end_time, 
                    long tech1_counter, 
                    string tech2, 
                    string tech2_start_time, 
                    string tech2_end_time, 
                    long tech2_counter, 
                    string tech3, 
                    string tech3_start_time, 
                    string tech3_end_time, 
                    long tech3_counter, 
                    string tech4, 
                    string tech4_start_time, 
                    string tech4_end_time, 
                    long tech4_counter, 
                    string tech5, 
                    string tech5_start_time, 
                    string tech5_end_time, 
                    long tech5_counter, 
                    string udf1, 
                    string udf2, 
                    string udf3, 
                    string udf4, 
                    string udf5) {
            return base.Channel.process_jobAsync(userid, job_counter, job_type, job_cn, job_no, job_date, job_status, job_summary, project_manager, po_number, work_description, tech1, tech1_start_time, tech1_end_time, tech1_counter, tech2, tech2_start_time, tech2_end_time, tech2_counter, tech3, tech3_start_time, tech3_end_time, tech3_counter, tech4, tech4_start_time, tech4_end_time, tech4_counter, tech5, tech5_start_time, tech5_end_time, tech5_counter, udf1, udf2, udf3, udf4, udf5);
        }
        
        public string process_tm(string userid, long job_cn, long job_no, string job_type) {
            return base.Channel.process_tm(userid, job_cn, job_no, job_type);
        }
        
        public System.Threading.Tasks.Task<string> process_tmAsync(string userid, long job_cn, long job_no, string job_type) {
            return base.Channel.process_tmAsync(userid, job_cn, job_no, job_type);
        }
        
        public string get_signature(long customerNumber, long jobNumber) {
            return base.Channel.get_signature(customerNumber, jobNumber);
        }
        
        public System.Threading.Tasks.Task<string> get_signatureAsync(long customerNumber, long jobNumber) {
            return base.Channel.get_signatureAsync(customerNumber, jobNumber);
        }
        
        public string savesignature(long job_cn, long job_no, int frm, string signature) {
            return base.Channel.savesignature(job_cn, job_no, frm, signature);
        }
        
        public System.Threading.Tasks.Task<string> savesignatureAsync(long job_cn, long job_no, int frm, string signature) {
            return base.Channel.savesignatureAsync(job_cn, job_no, frm, signature);
        }
        
        public string savefiles(long job_cn, string job_no, string title) {
            return base.Channel.savefiles(job_cn, job_no, title);
        }
        
        public System.Threading.Tasks.Task<string> savefilesAsync(long job_cn, string job_no, string title) {
            return base.Channel.savefilesAsync(job_cn, job_no, title);
        }
        
        public string get_time() {
            return base.Channel.get_time();
        }
        
        public System.Threading.Tasks.Task<string> get_timeAsync() {
            return base.Channel.get_timeAsync();
        }
    }
}
